- hosts: localhost
  tasks:
  - name: Run jekyll build
    command: "bundle exec jekyll build"

- hosts: remote
  become: yes
  tasks:
  - name: Ensure site directory exists
    file:
      path: "{{ site_directory }}"
      state: directory

  - name: Copy _site to remote site directory
    synchronize:
      src: _site/
      dest: "{{ site_directory }}"
      delete: yes

  - name: Install nginx
    package:
      name: nginx
      state: present

  ## TODO: Figure out how to bypass overriding Certbot managed section
  # - name: Copy nginx.conf template
  #   template:
  #     src: nginx.conf.template
  #     dest: "/etc/nginx/nginx.conf"
  #   notify: Restart nginx

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

  vars:
    site_directory: /var/www/html/
